{% set version = "5.1" %}

package:
  name: aocl-blas
  version: {{ version }}

source:
    url: https://github.com/amd/blis/archive/refs/tags/{{ version }}.tar.gz
    sha256: 4ab210cea8753f4be9646a3ad8e6b42c7d19380084a66312497c97278b8c76a4

build:
  number: 0
#  skip: true  # [win]

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("fortran") }}  # [not win]
    - llvm-openmp  # [not linux]
    - libgomp  # [linux]
    - make   # [not win]
    - ninja  # [win]
    - cmake
  host:
  run:

test:
  commands:
    - test -f $PREFIX/lib/libblis-mt${SHLIB_EXT}           # [unix]
    - test -f $PREFIX/include/blis.h                       # [unix]
    - if not exist %LIBRARY_INC%\\blis.h exit 1                       # [win]
    - if not exist %LIBRARY_LIB%\\AOCL-LibBlis-Win-MT-dll.dll exit 1  # [win]

about:
  home: https://www.amd.com/en/developer/aocl/dense.html
  license: BSD-3-Clause
  license_file: LICENSE
  summary: AMD's fork of BLIS optimized for AMD processors.
  description: |
    AOCL-BLAS is AMD's optimized version of BLAS targeted for AMD EPYC and Ryzen CPUs.
  dev_url: https://github.com/amd/blis

extra:
  recipe-maintainers:
    - chillenb
