schema_version: 1

context:
  version: 5.1

package:
  name: aocl-blas
  version: ${{ version }}

source:
  - url: https://github.com/amd/blis/archive/refs/tags/${{ version }}.tar.gz
    sha256: 4ab210cea8753f4be9646a3ad8e6b42c7d19380084a66312497c97278b8c76a4
    target_directory: aoclblas
  - url: https://github.com/amd/libflame/archive/refs/tags/${{ version }}.tar.gz
    sha256: 25524ba78b5952303369fa0859d217e44071144fd122a9dc3f72ed0bd73e3b2d
    target_directory: aocllapack
  - url: https://github.com/amd/aocl-utils/archive/refs/tags/${{ version }}.tar.gz
    sha256: 68d75e04013abe90ea8308a9bc99b99532233b6c7f937f35381563f4124c20a5
    target_directory: aoclutils

build:
  number: 0

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - if: not win
      then: ${{ compiler("fortran") }}
    - if: not linux
      then: llvm-openmp
    - if: linux
      then: libgomp
    - if: not win
      then: make
    - if: win
      then: ninja
    - cmake
  host:
  run:

tests:
  - script:
      - if: unix
        then: test -f $PREFIX/lib/libblis-mt${SHLIB_EXT}
      - if: unix
        then: test -f $PREFIX/include/blis.h
      - if: win
        then: if not exist %LIBRARY_INC%\\blis.h exit 1
      - if: win
        then: if not exist %LIBRARY_LIB%\\AOCL-LibBlis-Win-MT-dll.dll exit 1

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: "AMD's fork of BLIS optimized for AMD processors."
  description: |
    AOCL-BLAS is AMD's optimized version of BLAS targeted for AMD EPYC and Ryzen CPUs.
  homepage: https://www.amd.com/en/developer/aocl/dense.html
  repository: https://github.com/amd/blis

extra:
  recipe-maintainers:
    - chillenb
