schema_version: 1

context:
  version: 5.1

package:
  name: aocl-blas
  version: ${{ version }}

source:
    url: https://github.com/amd/blis/archive/refs/tags/${{ version }}.tar.gz
    sha256: 4ab210cea8753f4be9646a3ad8e6b42c7d19380084a66312497c97278b8c76a4

build:
  number: 0

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - if: not win
      then: ${{ compiler("fortran") }}
    - if: not linux
      then: llvm-openmp
    - if: linux
      then: libgomp
    - if: not win
      then: make
    - if: win
      then: ninja
    - cmake
  host:
  run:

tests:
  - script:
      - if: unix
        then: test -f $PREFIX/lib/libblis-mt${SHLIB_EXT}
      - if: unix
        then: test -f $PREFIX/include/blis.h
      - if: win
        then: if not exist %LIBRARY_INC%\\blis.h exit 1
      - if: win
        then: if not exist %LIBRARY_LIB%\\AOCL-LibBlis-Win-MT-dll.dll exit 1

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: "AMD's fork of BLIS optimized for AMD processors."
  description: |
    AOCL-BLAS is AMD's optimized version of BLAS targeted for AMD EPYC and Ryzen CPUs.
  homepage: https://www.amd.com/en/developer/aocl/dense.html
  repository: https://github.com/amd/blis

extra:
  recipe-maintainers:
    - chillenb
